version: "1"
module_version: 0.2.8

tests:
  - name: With older TF
    id: oldtf1
    terraform_version: 1.0.11

  # - name: Newer TF 1
  #   id: newtf1
  #   depends_on: ["oldtf1"]
  #   terraform_version:  1.1.1
    
  # - name: Newer TF 2
  #   id: newtf2
  #   depends_on: ["newtf1"]
  #   terraform_version: 1.1.2
    
  # - name: Newer TF 3
  #   id: newtf3
  #   depends_on: ["newtf2"]
  #   terraform_version: 1.1.3
    
  # - name: Newer TF 4
  #   id: newtf4
  #   depends_on: ["newtf3"]
  #   terraform_version: 1.1.4
