version: "1"
module_version: 0.2.0

tests:
  - name: With older TF
    id: oldtf1
    terraform_version: 1.0.11

  - name: Newer TF 1
    id: newtf1
    terraform_version: 1.1.1
    
  - name: Newer TF 2
    id: newtf2
    terraform_version: 1.1.2
    
  - name: Newer TF 3
    id: newtf3
    # depends_on: ["newtf4"] # circular
    terraform_version: 1.1.3
    
  - name: Newer TF 4
    id: newtf4
    depends_on: ["oldtf1", "newtf1", "newtf2", "newtf3"]
    terraform_version: 1.1.4
